#!/usr/bin/env Rscript

# Rebuild every committed artefact under outputs/ from the specs in library/tfl/.
#
#   Rscript qc/regenerate-library.R
#
# This is the "agents write source, the pipeline writes outputs" rule made
# executable: the whole outputs/ tree is reproducible from the two YAML files per
# display plus the pinned data package.
#
# t-ae-common is regenerated twice on purpose. Its committed history is the
# worked example of the change-request loop (design §4.3): v001 is the display as
# first specified, v002 is the display after a medical-writer change request was
# applied as a spec edit. The script replays that history so the iteration ledger
# on disk is a real record rather than a hand-written one.

#
# Coverage, stated rather than assumed: this script replays the displays it
# names below and nothing else. The efficacy, CIBIC+, time-to-event and
# disposition displays added in v0.3.0 (#41–#53) were generated by direct
# regenerate() calls and are NOT replayed here, so wiping outputs/ would lose
# them. The guard below refuses to start unless every display in library/tfl/
# is covered; extend the script before running it.

suppressWarnings(suppressMessages(library(pkgload)))

root <- normalizePath(file.path(dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1])), ".."))
options(opencsr.root = root)
pkgload::load_all(file.path(root, "pipeline"), quiet = TRUE)

covered <- c(
  "t-demographics", "t-disposition", "t-exposure", "t-ae-overview", "l-ae-serious",
  "t-vitals", "t-vitals-change", "t-weight", "t-conmeds", "t-ae-common"
)
uncovered <- setdiff(display_slugs(root), covered)
if (length(uncovered)) {
  stop(
    "qc/regenerate-library.R replays ", length(covered), " displays and would delete the ",
    "committed outputs of ", length(uncovered), " it does not replay: ",
    paste(uncovered, collapse = ", "), ". Extend the script before running it.",
    call. = FALSE
  )
}

# ---- start from a clean tree ------------------------------------------------

unlink(list.files(file.path(root, "outputs"), full.names = TRUE), recursive = TRUE)
for (slug in display_slugs(root)) {
  unlink(file.path(display_dir(slug, root), "iterations.yaml"))
}

specs <- lapply(display_slugs(root), function(s) read_analysis_spec(s, root))
needed <- unique(c("adsl", unlist(lapply(specs, function(s) c(s$dataset, s$denominator)))))
message("Preparing data: ", paste(needed, collapse = ", "))
# History first: the v0 iterations were built on the pharmaverse re-derivation,
# and t-exposure read its ADEX. They are replayed on that lane, with the spec
# t-exposure had then (qc/history/), so the ledger records what was built rather
# than what would be built now. The v0.4.0 block below regenerates every one of
# them on the pilot's own package (D0032 R2, #60).
data_pv <- prepare_data(datasets = c("adsl", "adae", "adex", "advs"), sources = "pharmaverseadam")
data <- prepare_data(datasets = setdiff(needed, c("adex", "adlb")))

# ---- nine displays, one iteration each --------------------------------------

initial <- c(
  "t-demographics", "t-disposition", "t-exposure", "t-ae-overview", "l-ae-serious",
  # The vital signs, weight and concomitant-medication group. Their change
  # requests read differently from the five above because they were written
  # against a document that already exists: each names the table of the reference
  # clinical study report it targets, so the ledger records what the display was
  # for, not just that it was generated.
  "t-vitals", "t-vitals-change", "t-weight", "t-conmeds"
)
targets <- c(
  "t-vitals" = "Table 14-7.01",
  "t-vitals-change" = "Table 14-7.02",
  "t-weight" = "Table 14-7.03",
  "t-conmeds" = "Table 14-7.04"
)
exp_dir <- display_dir("t-exposure", root)
exp_now <- list(
  analysis = readLines(file.path(exp_dir, "analysis.yaml")),
  display = readLines(file.path(exp_dir, "display.yaml"))
)
file.copy(file.path(root, "qc", "history", "t-exposure", "analysis.yaml"), file.path(exp_dir, "analysis.yaml"), overwrite = TRUE)
file.copy(file.path(root, "qc", "history", "t-exposure", "display.yaml"), file.path(exp_dir, "display.yaml"), overwrite = TRUE)
on.exit({
  writeLines(exp_now$analysis, file.path(exp_dir, "analysis.yaml"))
  writeLines(exp_now$display, file.path(exp_dir, "display.yaml"))
}, add = TRUE)

for (slug in initial) {
  id <- read_analysis_spec(slug, root)$regulatory_id
  request <- if (slug %in% names(targets)) {
    paste0(
      "Initial generation of ", id, ", targeting ", targets[[slug]],
      " of the reference clinical study report for this study."
    )
  } else {
    paste0("Initial generation of ", id, " from the statistical analysis plan shell.")
  }
  m <- regenerate(slug, root, change_request = request, actor = "@jwildfire", data = data_pv, sources = "pharmaverseadam")
  message(sprintf("%-16s %s  %d ARD rows", slug, m$version, m$ard_rows))
}

# ---- t-ae-common: the change-request loop, replayed -------------------------

ae_dir <- display_dir("t-ae-common", root)
analysis_path <- file.path(ae_dir, "analysis.yaml")
display_path <- file.path(ae_dir, "display.yaml")
after <- list(analysis = readLines(analysis_path), display = readLines(display_path))

# v001: the display as originally specified — no pooled Total column.
before_analysis <- sub("^total: true$", "total: false", after$analysis)
before_display <- sub(
  '^  order: \\[Placebo, "Xanomeline Low Dose", "Xanomeline High Dose", Total\\]$',
  '  order: [Placebo, "Xanomeline Low Dose", "Xanomeline High Dose"]',
  after$display
)
before_display <- before_display[!grepl("^  - \"The Total column pools", before_display)]
stopifnot(!identical(before_analysis, after$analysis), !identical(before_display, after$display))

writeLines(before_analysis, analysis_path)
writeLines(before_display, display_path)
m1 <- regenerate(
  "t-ae-common", root,
  change_request = paste(
    "Initial generation of AET02 from the statistical analysis plan shell:",
    "treatment-emergent adverse events by system organ class and preferred term,",
    "with a 5% threshold on the in-text variant."
  ),
  actor = "@jwildfire", data = data_pv, sources = "pharmaverseadam"
)
message(sprintf("%-16s %s  %d ARD rows", "t-ae-common", m1$version, m1$ard_rows))

# v002: the change request, applied as a spec edit and regenerated.
writeLines(after$analysis, analysis_path)
writeLines(after$display, display_path)
m2 <- regenerate(
  "t-ae-common", root,
  change_request = paste(
    "Change request CR-001 (medical writer, Section 12.2.1 review):",
    "add an All Subjects (Total) column to AET02 so the in-text summary can quote",
    "a pooled overall rate alongside the by-arm rates.",
    "Applied as a spec edit - analysis.yaml `total: false` -> `true`,",
    "display.yaml `columns.order` gains Total - and regenerated; no output was hand-edited."
  ),
  actor = "@medical-writer", data = data_pv, sources = "pharmaverseadam"
)
message(sprintf("%-16s %s  %d ARD rows", "t-ae-common", m2$version, m2$ard_rows))

# ---- v0.4.0: one study — every display on the pilot's own package -----------

writeLines(exp_now$analysis, file.path(exp_dir, "analysis.yaml"))
writeLines(exp_now$display, file.path(exp_dir, "display.yaml"))
for (slug in covered) {
  request <- if (slug == "t-exposure") {
    paste(
      "One study (D0032 R2, #60): rebuilt from ADSL's AVGDD and CUMDOSE for the safety",
      "population and the Week 24 completers, as Table 14-4.01 of the reference report",
      "summarises them. No exposure dataset is read."
    )
  } else {
    paste(
      "One study (D0032 R2, #60): read the CDISC pilot's own ADaM package, which assigns",
      "every subject the arm the rest of the report uses. Spec unchanged; lane changed."
    )
  }
  m <- regenerate(slug, root, change_request = request, actor = "@obotclaw", data = data)
  message(sprintf("%-16s %s  %d ARD rows  [pilot package]", slug, m$version, m$ard_rows))
}

message("\nLibrary regenerated: ", length(covered), " displays.")
